---
apiVersion: kubeadm.k8s.io/v1beta3
bootstrapTokens:
  - groups:
      - system:bootstrappers:kubeadm:default-node-token
    token: "{{ bootstrap_token }}"
    ttl: 24h0m0s
    usages:
      - signing
      - authentication
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: "{{ groups["masternode"][0] }}"
  bindPort: 6443
nodeRegistration:
  criSocket: unix:///var/run/cri-dockerd.sock
  imagePullPolicy: IfNotPresent
  imagePullSerial: true
  name: "{{ hostname }}"
  taints:
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
---
apiServer: {}
apiVersion: kubeadm.k8s.io/v1beta3
caCertificateValidityPeriod: 87600h0m0s
certificateValidityPeriod: 8760h0m0s
certificatesDir: /etc/kubernetes/pki
clusterName: "{{ cluster_name }}"
controllerManager: {}
encryptionAlgorithm: RSA-2048
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: "registry.k8s.io"
kind: ClusterConfiguration
kubernetesVersion: v1.28.14
networking:
  dnsDomain: cluster.local
  podSubnet: "{{ podSubnet }}"
proxy: {}
scheduler: {}
